//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsobyZaginioneFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class osoba
    {
        public int Id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string alias { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> tel { get; set; }
    
        public virtual city city { get; set; }
        public virtual status status { get; set; }
    }
}
